name: Merge Staging to Main with Fast-Forward

on:
  workflow_dispatch: # Triggered manually

jobs:
  merge-with-approval:
    runs-on: ubuntu-latest

    # Define the environment and require approval
    environment: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history for merging

      - name: Fetch all branches
        run: git fetch --all

      - name: Show diff between main and staging
        run: git diff origin/main...origin/staging

      - name: Wait for approval
        run: |
          echo "Waiting for approval to merge staging into main."
          # The merge will be blocked until approval is granted via branch protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform Fast-Forward Merge
        run: |
          git checkout main
          git merge --ff-only origin/staging
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
