name: Merge Staging to Main with Fast-Forward
permissions:
  issues: write  # Grants write access to issues
  contents: write  # Grants read-only access to the repository contents

on:
  workflow_dispatch: # Triggered manually

jobs:
  merge-with-approval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history for merging

      - name: Fetch all branches
        run: git fetch --all

      - name: Show diff between main and staging
        id: show_diff
        run: |
          echo "Generating diff..."
          git diff origin/main origin/staging > diff_output.txt
          # Write the diff output to an environment file instead of using set-output
          echo "DIFF_OUTPUT=$(cat diff_output.txt)" >> $GITHUB_ENV

      - name: Wait for approval
        run: |
          echo "Waiting for approval to merge staging into main."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Approval Issue
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}  # Use the correct token for access
          approvers: "${{ github.actor }}" 
          minimum-approvals: 1
          issue-title: "Deploying changes to prod from staging"
          issue-body: |
            Please approve or deny the deployment.

            ### Changes:
            ```diff
            ${{ env.DIFF_OUTPUT }}  # Include the full diff output from the environment variable
            ```
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      
      - name: Perform Fast-Forward Merge
        run: |
          git checkout main
          git merge --ff-only origin/staging
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
