name: Manual Merge from Staging to Main

on:
  workflow_dispatch: # Manually triggered action

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to create PR and push changes
      pull-requests: write # Needed to create PR and merge it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history for git operations

      - name: Fetch all branches
        run: git fetch --all

      - name: Create Pull Request from Staging to Main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: staging
          title: "Merge Staging to Main"
          body: "This PR merges the staging branch into the main branch."
          draft: false # Set to false to directly create the PR

      - name: Wait for PR Approval
        uses: flybayer/wait-for-approval-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.create-pull-request.outputs.pull-request-number }}
          approval-count: 1 # The number of approvals needed

      - name: Merge the Pull Request
        run: |
          PR_NUMBER=${{ steps.create-pull-request.outputs.pull-request-number }}
          gh pr merge $PR_NUMBER --repo ${{ github.repository }} --merge --admin --ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Merged Changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
